
# SHARED or STATIC, default build static
set(X_BUILD_STATIC 0 CACHE BOOL 0 FORCE)
# sln Folders
set_property(GLOBAL PROPERTY USE_FOLDERS On)
# include dir
set(X_INCLUDE ${PROJECT_SOURCE_DIR}/include)
# install
if(MSVC)
    if(NOT DEFINED X_INSTALL_PREFIX)
        set(X_INSTALL_PREFIX "${PROJECT_SOURCE_DIR}/install" CACHE STRING "${PROJECT_SOURCE_DIR}/install" FORCE)
    endif()
endif()

if(DEFINED X_INSTALL_PREFIX)
    set(CMAKE_INSTALL_PREFIX ${X_INSTALL_PREFIX})
endif()

macro(install_module MODULE_NAME)
    install(TARGETS ${MODULE_NAME}
        RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
        LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
        ARCHIVE DESTINATION ${CMAKE_INSTALL_LIBDIR}
    )
endmacro()

# output
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
